target-version = "py312"
line-length = 88
indent-width = 4

exclude = [
  ".git",
  ".venv",
  "venv",
  "__pycache__",
  "build",
  "dist",
  ".mypy_cache",
  ".ruff_cache",
  ".pytest_cache",
]

[lint]
select = [
  "E", "W", "F", "I", "B", "C4", "UP", "SIM", "RUF", "RET", "D", "C", "PL"
]
ignore = [
  "E501",  # don't nag about line length (formatter handles it)
  "B008",  # allow function calls in default arguments
  "RET504",   # unnecessary assignment before return
]
fixable = ["ALL"]

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
